-- Generated by hyprconf2lua v1.3.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- See https://wiki.hyprland.org/Configuring/Monitors/

-- monitor = , 1920x1200@120, 0x0x, 1.0

hl.monitor({
    output   = "DP-3",
    mode     = "2560x1080@200",
    position = "0x0",
    scale    = 1.0,
})

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1200@120",
    position = "-1920x0",
    scale    = 1.0,
})

local monitor_index = {
    ["DP-3"] = 0,
    ["HDMI-A-1"] = 1,
}

-- monitor = , preferred, auto, 1.0

-- Bind workspace

hl.workspace_rule({
    workspace = "r[1-10]",
    monitor = "DP-3",
})

hl.workspace_rule({
    workspace = "r[11-20]",
    monitor = "HDMI-A-1",
})

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more

-- Execute your favorite apps at launch

-- exec-once = waybar & hyprpaper & firefox

-- Source a file (multi-file configs)

-- source = ~/.config/hypr/myColors.conf

-- For all categories, see https://wiki.hyprland.org/Configuring/Variables/

hl.config({
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        follow_mouse = 1,
        touchpad = {
            natural_scroll = true,
        },
        --	tablet {
        --		output = DP-2
        --       # relative_input = true
        --		region_position = 0 0
        --		region_size = 2560 1600
        --	}
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
        accel_profile = "flat",
    },
})

hl.config({
    general = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        gaps_in = 4,
        gaps_out = 8,
        border_size = 1,
        allow_tearing = true,
        layout = "dwindle",
        col = {
            active_border = "rgba(d3e4c9ff)",
            inactive_border = "rgba(2222227f)",
        },
    },
})

hl.config({
    decoration = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        rounding = 0,
        shadow = {
            enabled = true,
            color = "rgba(0000005f)",
            color_inactive = "rgba(0000003f)",
            range = 25,
        },
        blur = {
            enabled = true,
            size = 1,
            passes = 3,
            contrast = 1.0,
            -- noise = 0.05
            -- special = true
        },
    },
})

hl.config({
    cursor = {
        no_hardware_cursors = true,
    },
})

hl.config({
    animations = {
        enabled = true,
        -- Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    },
})

hl.curve( "windowPop", { type = "spring", mass = 1, stiffness = 400, dampening = 70 })

hl.curve( "layersFade", { type = "spring", mass = 1, stiffness = 500, dampening = 70 })

hl.curve( "workspaceMove", { type = "spring", mass = 1, stiffness = 300, dampening = 70 })

hl.animation({ leaf = "windows", enabled = true, speed = 1, spring = "windowPop", style = "popin 90%"})

hl.animation({ leaf = "layers", enabled = true, speed = 1, spring = "layersFade", style = "fade"})

hl.animation({ leaf = "workspaces", enabled = true, speed = 1, spring = "workspaceMove", style = "slide"})

hl.config({
    dwindle = {
        -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
        --    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        preserve_split = true,
        -- you probably want this
        split_width_multiplier = 1.33,
    },
})

hl.config({
    misc = {
        --force_hypr_chan = true
        mouse_move_enables_dpms = true,
        key_press_enables_dpms = true,
        render_unfocused_fps = 60,
        enable_anr_dialog = false,
        --disable_splash_rendering = true
    },
})

-- Layer Rules

-- layerrule = blur, waybar

-- layerrule = ignorezero, waybar

hl.layer_rule({
    match = {
        namespace = "match:namespace notifications",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "match:namespace notifications",
    },
    ignore_alpha = 0,
})

hl.layer_rule({
    match = {
        namespace = "match:namespace launcher",
    },
    blur = true,
})

hl.layer_rule({
    match = {
        namespace = "match:namespace launcher",
    },
    ignore_alpha = 0,
})

-- Window Rules

-- windowrulev2 = float,class:(.*)

hl.window_rule({
    name  = "match_class_alacritt",
    match = {
        class = "Alacritty",
    },
    tile = true
    -- TODO: review rule: "match:class Alacritty"
})

hl.window_rule({
    name  = "match_class_qq",
    match = {
        class = "QQ",
    },
    float = true
    -- TODO: review rule: "match:class QQ"
})

-- QQ Popups

hl.window_rule({
    name  = "match_title_volume_c",
    match = {
        title = "Volume Control",
    },
    float = true
    -- TODO: review rule: "match:title Volume Control"
})

-- Volume Control

hl.window_rule({
    name  = "match_class_steam",
    match = {
        class = "Steam",
    },
    float = true
    -- TODO: review rule: "match:class steam"
})

-- Steam Popups

hl.window_rule({
    name  = "match_title_qt5_conf",
    match = {
        title = "Qt5 Configuration Tool",
    },
    float = true
    -- TODO: review rule: "match:title Qt5 Configuration Tool"
})

-- Qt5

hl.window_rule({
    name  = "match_title_qt6_conf",
    match = {
        title = "Qt6 Configuration Tool",
    },
    float = true
    -- TODO: review rule: "match:title Qt6 Configuration Tool"
})

-- Qt6

hl.window_rule({
    name  = "match_title_fcitx_co",
    match = {
        title = "Fcitx Configuration",
    },
    float = true
    -- TODO: review rule: "match:title Fcitx Configuration"
})

-- Fcitx Config

hl.window_rule({
    name  = "match_class_org_gnom",
    match = {
        class = "org.gnome.Nautilus",
    },
    float = true
    -- TODO: review rule: "match:class org.gnome.Nautilus"
})

-- Nautilus Popups

hl.window_rule({
    name  = "match_class_firefox",
    match = {
        class = "firefox",
        title = "Library",
    },
    float = true
    -- TODO: review rule: "match:class firefox"
})

-- Firefox Popups

hl.window_rule({
    name  = "match_class_vlc",
    match = {
        class = "vlc",
    },
    float = true
    -- TODO: review rule: "match:class vlc"
})

-- VLC Popups

hl.window_rule({
    name  = "match_class_qemu__",
    match = {
        class = "qemu.*",
    },
    float = true
    -- TODO: review rule: "match:class qemu.*"
})

-- QEMU

hl.window_rule({
    name  = "match_class_org_tele",
    match = {
        class = "org.telegram.desktop",
        title = "Media viewer"
    },
    float = true
    -- TODO: review rule: "match:class org.telegram.desktop"
})

hl.window_rule({
    name  = "match_class_com_st_a",
    match = {
        class = "com.st.app.Main",
    },
    float = true
    -- TODO: review rule: "match:class com.st.app.Main"
})

hl.window_rule({
    name  = "match_class_ltspice_",
    match = {
        class = "ltspice.exe",
    },
    float = true
    -- TODO: review rule: "match:class ltspice.exe"
})

hl.window_rule({
    name  = "match_class_xdg-desk",
    match = {
        class = "xdg-desktop-portal-gtk",
    },
    float = true
    -- TODO: review rule: "match:class xdg-desktop-portal-gtk"
})

-- pinned window

hl.window_rule({
    name  = "match_pin_true",
    match = {
        pin = true,
    },
    border_color = "rgb(598da8)"
    -- TODO: review rule: "match:pin true"
})

-- always render

hl.window_rule({
    name  = "match_class_vseeface",
    match = {
        class = "vseeface.exe",
    },
    render_unfocused = true
    -- TODO: review rule: "match:class vseeface.exe"
})

-- Variables

local proxy_socks5 = "socks5://localhost:1080"

local proxy_http = "http://localhost:1081"

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more

local mainMod = "SUPER"

-- Function Key bindings

hl.bind("xf86audiomute", hl.dsp.exec_cmd("pactl -- set-sink-mute @DEFAULT_SINK@ toggle"))

hl.bind("xf86audiolowervolume", hl.dsp.exec_cmd("pactl -- set-sink-volume @DEFAULT_SINK@ -5%"))

hl.bind("xf86audioraisevolume", hl.dsp.exec_cmd("pactl -- set-sink-volume @DEFAULT_SINK@ +5%"))

hl.bind("xf86audiomicmute", hl.dsp.exec_cmd("pactl -- set-source-mute @DEFAULT_SOURCE@ toggle"))

hl.bind("xf86monbrightnessdown", hl.dsp.exec_cmd("blight -d backlight/amdgpu_bl1 set -25.5"))

hl.bind("xf86monbrightnessup", hl.dsp.exec_cmd("blight -d backlight/amdgpu_bl1 set +25.5"))

-- Hyprland hotkeys

hl.bind(mainMod .. " + " .. "C", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "T", hl.dsp.exec_cmd("alacritty"))

hl.bind(mainMod .. " + " .. "M", hl.dsp.exit())

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("[float] nautilus --new-window"))

hl.bind(mainMod .. " + " .. "V", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "R", hl.dsp.exec_cmd("sh -c \"$(tofi-drun)\""))




hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle

-- bind = $mainMod, J, togglesplit, # dwindle

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

-- TODO: manual review (unknown dispatcher: bringactivetotop)
-- hl.bind("$mainMod + U", hl.dsp.bringactivetotop())

hl.bind(mainMod .. " + " .. "Z", hl.dsp.window.pin())

-- Hyprland some reload exec-once

hl.bind(mainMod .. " + " .. "CTRL + ALT" .. " + " .. "R", hl.dsp.exec_cmd("killall waybar; waybar"))

hl.bind(mainMod .. " + " .. "CTRL + ALT" .. " + " .. "R", hl.dsp.exec_cmd("killall fcixt5; fcitx5"))

-- Screenshot

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.exec_raw("slurp | grim -g - - | wl-copy"))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "W", hl.dsp.exec_cmd("grim -g $(hyprctl -j activewindow | jq -r ' \\(.at[0]),\\(.at[1]) \\(.size[0])x\\(.size[1]) ')-| wl-copy"))
-- TODO : NEED TO RECREATE

hl.bind("print", hl.dsp.exec_cmd("grim-| wl-copy"))

-- OBS

hl.bind(mainMod .. " + " .. "HOME", hl.dsp.exec_cmd("obs-cli recording start --host 127.0.0.1 --port 50000"))

hl.bind(mainMod .. " + " .. "END", hl.dsp.exec_cmd("obs-cli recording stop --host 127.0.0.1 --port 50000"))

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

local switch_script = "~/.config/hypr/switch_workspace.sh"

-- Switch workspaces with mainMod + [0-9]

-- for i = 1, 10 do
--     local key = i % 10 -- 10 maps to key 02
--     hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
--     hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
-- end

for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key, function()
        local cur_monitor = hl.get_active_monitor().name
        local target_workspace = monitor_index[cur_monitor] * 10 + i
        hl.dispatch(hl.dsp.workspace.move({ workspace = target_workspace, monitor = cur_monitor}))
        hl.dispatch(hl.dsp.focus({ workspace = target_workspace }))
    end)
    hl.bind(mainMod .. " + SHIFT + " .. key, function ()
        local cur_monitor = hl.get_active_monitor().name
        local target_workspace = monitor_index[cur_monitor] * 10 + i
        hl.dispatch(hl.dsp.workspace.move({ workspace = target_workspace, monitor = cur_monitor}))
        hl.dispatch(hl.dsp.window.move({ workspace = target_workspace }))
    end)
end

hl.bind(mainMod .. " + X", hl.dsp.workspace.toggle_special())
hl.bind(mainMod .. " + SHIFT + X", hl.dsp.window.move({ workspace = "special" }))

-- TODO: manual review (unknown dispatcher: movecurrentworkspacetomonitor)
-- hl.bind("$mainMod + SHIFT + comma", hl.dsp.movecurrentworkspacetomonitor("l"))

-- TODO: manual review (unknown dispatcher: movecurrentworkspacetomonitor)
-- hl.bind("$mainMod + SHIFT + period", hl.dsp.movecurrentworkspacetomonitor("r"))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Lock

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "L", hl.dsp.exec_cmd("hyprlock"))

-- Input Methods

hl.env("XMODIFIERS", "@im=fcitx")

-- This line is removed since it causes GTK applications crash (if without Wayland support)

-- env = GTK_IM_MODULE, wayland

-- env = QT_IM_MODULE, wayland

hl.env("SDL_IM_MODULE", "fcitx")

-- SDL wayland

-- This is deprecated since many clients does not support wayland

-- env = SDL_VIDEODRIVER, "wayland,x11"

-- Cursor

hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")

hl.env("HYPRCURSOR_SIZE", 32)

hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")

hl.env("XCURSOR_SIZE", 32)

-- NVIDIA Fix

hl.env("LIBVA_DRIVER_NAME", "nvidia")

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("GBM_BACKEND", "nvidia-drm")

hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")

hl.env("WLR_NO_HARDWARE_CURSORS", 1)

-- Other Environment

hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")

-- Proxy

hl.env("ALL_PROXY", "socks5://localhost:1080")

hl.env("HTTP_PROXY", "http://localhost:1081")

hl.env("HTTPS_PROXY", "http://localhost:1081")

hl.env("all_proxy", "socks5://localhost:1080")

hl.env("http_proxy", "http://localhost:1081")

hl.env("https_proxy", "http://localhost:1081")

hl.env("NO_PROXY", "127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16")

-- Auto start




-- exec-once = swayidle timeout 300 'hyprctl dispatcher dpms off'


-- Agent


-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("waybar")
    hl.exec_cmd("fcitx5")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
end)
